name: Convert GitHub Issue to Markdown and Update Sitemap

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate markdown from issue
        run: |
          echo "🧩 Starting issue conversion..."

          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          LABELS=$(echo "${{ toJson(github.event.issue.labels) }}" | tr '[:upper:]' '[:lower:]')

          if echo "$LABELS" | grep -q "testimonial"; then
            FOLDER="tests"
          else
            FOLDER="posts"
          fi

          mkdir -p "$FOLDER"

          SLUG=$(echo "$TITLE" | iconv -c -t ascii | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
          DATE=$(date +%Y-%m-%d)
          FILENAME="$FOLDER/${DATE}-${SLUG}.md"

          echo "📄 Creating file: $FILENAME"

          echo "---" > "$FILENAME"
          echo "title: \"$TITLE\"" >> "$FILENAME"
          echo "author: \"Admin\"" >> "$FILENAME"
          echo "tags: \"\"" >> "$FILENAME"
          echo "date: \"$DATE\"" >> "$FILENAME"
          echo "image: \"\"" >> "$FILENAME"
          echo "---" >> "$FILENAME"
          echo "" >> "$FILENAME"
          echo "$BODY" >> "$FILENAME"

      - name: Generate sitemap
        run: |
          echo "REACT_APP_SITE_URL=https://www.strawket.in" > .env
          echo "REACT_APP_CONTENT_REPO=premierchessacademy/strawket-content" >> .env
          echo "REACT_APP_CONTENT_BRANCH=main" >> .env
          node generate-sitemap.js

      - name: Commit markdown and sitemap
        uses: EndBug/add-and-commit@v9
        with:
          add: 'posts/ tests/ public/sitemap.xml'
          message: "📄 Created post + updated sitemap: ${{ github.event.issue.title }}"
          default_author: github_actions
